# Generated by Django 5.1.1 on 2024-09-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
