# Generated by Django 5.1.1 on 2024-09-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
