# Generated by Django 5.1.1 on 2024-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cartorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'Cash on Delivery'), ('credit card', 'Credit Card'), ('paypal', 'PayPal')], max_length=30),
        ),
    ]
